const resizeLayout = {
  lg: [
    { w: 3, h: 1, x: 0, y: 0, i: 'a', static: true, isDraggable: false, isResizable: false },
    { w: 7, h: 4, x: 3, y: 0, i: 'b', static: true, isDraggable: false, isResizable: false },
    { w: 2, h: 1, x: 10, y: 0, i: 'd', static: true, isDraggable: false, isResizable: false },
    { w: 1, h: 1, x: 0, y: 1, i: 'c', static: false, isDraggable: true, isResizable: false },

    { w: 3, h: 1, x: 0, y: 2, i: 'e', static: false, isDraggable: false, isResizable: true },
  ],
  md: [
    { w: 3, h: 1, x: 0, y: 0, i: 'a', static: false, isDraggable: false, isResizable: true },
    { w: 5, h: 3, x: 3, y: 0, i: 'b', static: true, isDraggable: false, isResizable: false },
    { w: 3, h: 1, x: 0, y: 1, i: 'd', static: false, isDraggable: true, isResizable: true },
    { w: 3, h: 1, x: 0, y: 2, i: 'e', static: false, isDraggable: true, isResizable: true },
    { w: 9, h: 1, x: 1, y: 3, i: 'c', static: false, isDraggable: true, isResizable: true },
  ],
  sm: [
    { i: 'a', x: 0, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'b', x: 1, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'c', x: 0, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'd', x: 1, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'e', x: 0, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
  ],
  xs: [
    { i: 'a', x: 0, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'b', x: 1, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'c', x: 0, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'd', x: 1, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'e', x: 0, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
  ],
  xxs: [
    { i: 'a', x: 0, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'b', x: 1, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'c', x: 0, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'd', x: 1, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'e', x: 0, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
  ],
};

const fixedLayout = {
  lg: [
    {
      w: 1,
      h: 1,
      x: 0,
      y: 0,
      i: 'A',

      static: false,
      isDraggable: false,
      isResizable: false,
    },
    {
      w: 1,
      h: 1,
      x: 1,
      y: 0,
      i: 'D',

      static: false,
      isDraggable: false,
      isResizable: false,
    },
    {
      w: 1,
      h: 1,
      x: 0,
      y: 1,
      i: 'B',

      static: false,
      isDraggable: true,
      isResizable: false,
    },
    {
      w: 1,
      h: 1,
      x: 1,
      y: 1,
      i: 'F',

      static: false,
      isDraggable: false,
      isResizable: false,
    },
    {
      w: 1,
      h: 1,
      x: 0,
      y: 2,
      i: 'C',

      static: false,
      isDraggable: false,
      isResizable: false,
    },
    {
      w: 1,
      h: 1,
      x: 1,
      y: 2,
      i: 'H',

      static: false,
      isDraggable: false,
      isResizable: false,
    },
    {
      w: 1,
      h: 1,
      x: 0,
      y: 3,
      i: 'E',

      static: false,
      isDraggable: false,
      isResizable: false,
    },
    {
      w: 1,
      h: 1,
      x: 0,
      y: 4,
      i: 'G',

      static: false,
      isDraggable: false,
      isResizable: false,
    },
  ],
  md: [
    { i: 'A', x: 0, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'B', x: 1, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'C', x: 0, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'D', x: 1, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'E', x: 0, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'F', x: 1, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'G', x: 0, y: 3, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'H', x: 1, y: 3, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
  ],
  sm: [
    { i: 'A', x: 0, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'B', x: 1, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'C', x: 0, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'D', x: 1, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'E', x: 0, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'F', x: 1, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'G', x: 0, y: 3, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'H', x: 1, y: 3, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
  ],
  xs: [
    { i: 'A', x: 0, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'B', x: 1, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'C', x: 0, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'D', x: 1, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'E', x: 0, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'F', x: 1, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'G', x: 0, y: 3, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'H', x: 1, y: 3, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
  ],
  xxs: [
    { i: 'A', x: 0, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'B', x: 1, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'C', x: 0, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'D', x: 1, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'E', x: 0, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'F', x: 1, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'G', x: 0, y: 3, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: 'H', x: 1, y: 3, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
  ],
};

const demoLayout = {
  lg: [
    {
      w: 3,
      h: 1,
      x: 0,
      y: 0,
      i: '1',

      static: true,
      isDraggable: false,
      isResizable: false,
    },
    {
      w: 7,
      h: 4,
      x: 3,
      y: 0,
      i: '2',

      static: true,
      isDraggable: false,
      isResizable: false,
    },
    {
      w: 2,
      h: 1,
      x: 10,
      y: 0,
      i: '4',

      static: true,
      isDraggable: false,
      isResizable: false,
    },
    {
      w: 1,
      h: 1,
      x: 0,
      y: 1,
      i: '3',

      static: false,
      isDraggable: true,
      isResizable: false,
    },
    {
      w: 2,
      h: 1,
      x: 1,
      y: 1,
      i: '6',

      static: false,
      isDraggable: false,
      isResizable: true,
    },
    {
      w: 2,
      h: 3,
      x: 10,
      y: 1,
      i: '8',

      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 3,
      h: 1,
      x: 0,
      y: 2,
      i: '5',

      static: false,
      isDraggable: false,
      isResizable: true,
    },
    {
      w: 3,
      h: 1,
      x: 0,
      y: 3,
      i: '7',

      static: false,
      isDraggable: false,
      isResizable: true,
    },
  ],
  md: [
    {
      w: 3,
      h: 1,
      x: 0,
      y: 0,
      i: '1',

      static: false,
      isDraggable: false,
      isResizable: true,
    },
    {
      w: 5,
      h: 3,
      x: 3,
      y: 0,
      i: '2',

      static: true,
      isDraggable: false,
      isResizable: false,
    },
    {
      w: 2,
      h: 2,
      x: 8,
      y: 0,
      i: '6',

      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 3,
      h: 1,
      x: 0,
      y: 1,
      i: '4',

      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 3,
      h: 1,
      x: 0,
      y: 2,
      i: '5',

      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 2,
      h: 1,
      x: 8,
      y: 2,
      i: '7',

      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 1,
      h: 1,
      x: 0,
      y: 3,
      i: '8',

      static: false,
      isDraggable: false,
      isResizable: false,
    },
    {
      w: 9,
      h: 1,
      x: 1,
      y: 3,
      i: '3',

      static: false,
      isDraggable: true,
      isResizable: true,
    },
  ],
  sm: [
    { i: '1', x: 0, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '2', x: 1, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '3', x: 0, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '4', x: 1, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '5', x: 0, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '6', x: 1, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '7', x: 0, y: 3, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '8', x: 1, y: 3, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
  ],
  xs: [
    { i: '1', x: 0, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '2', x: 1, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '3', x: 0, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '4', x: 1, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '5', x: 0, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '6', x: 1, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '7', x: 0, y: 3, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '8', x: 1, y: 3, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
  ],
  xxs: [
    { i: '1', x: 0, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '2', x: 1, y: 0, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '3', x: 0, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '4', x: 1, y: 1, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '5', x: 0, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '6', x: 1, y: 2, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '7', x: 0, y: 3, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
    { i: '8', x: 1, y: 3, w: 1, h: 1, isDraggable: false, isResizable: false, static: false },
  ],
};

export { resizeLayout, fixedLayout, demoLayout };
